#!/bin/bash
# MKBS Core - Configuration management
# Handles build configuration and target profiles

# Default configuration
declare -A MKBS_CONFIG=(
    [target]="x86_64"
    [profile]="base"
    [arch]="x86_64"
    [kernel]="linux"
    [libc]="musl"
    [init]="openrc"
    [shell]="bash"
    [compiler]="gcc"
    [optimize]="-O2"
    [jobs]="$(nproc 2>/dev/null || echo 4)"
)

# Supported targets
declare -A MKBS_TARGETS=(
    [x86_64]="x86_64-linux-musl"
    [aarch64]="aarch64-linux-musl"
    [armv7l]="arm-linux-musleabihf"
    [riscv64]="riscv64-linux-musl"
)

# Build profiles
declare -A MKBS_PROFILES=(
    [minimal]="kernel coreutils musl busybox"
    [base]="kernel coreutils musl bash openrc util-linux e2fsprogs"
    [desktop]="base xorg mesa wayland gnome-shell firefox"
    [server]="base nginx postgresql openssh docker"
    [development]="base gcc binutils gdb make cmake meson"
)

# Configuration file
MKBS_CONFIG_FILE="${MOONOS_ROOT}/mkbs.conf"

# Initialize configuration
mkbs_init_config() {
    log_debug "Initializing build configuration"

    # Load saved configuration if exists
    if [[ -f "$MKBS_CONFIG_FILE" ]]; then
        log_info "Loading configuration from $MKBS_CONFIG_FILE"
        source "$MKBS_CONFIG_FILE"
    fi

    # Set defaults for unset values
    MKBS_ARCH="${MKBS_TARGETS[${MKBS_CONFIG[target]}]:-x86_64-linux-musl}"
    MKBS_JOBS="${MKBS_CONFIG[jobs]:-$(nproc 2>/dev/null || echo 4)}"

    # Set directory paths
    MKBS_SYSROOT="${MOONOS_ROOT}/sysroot/${MKBS_CONFIG[target]}"
    MKBS_TOOLCHAIN="${MOONOS_ROOT}/toolchain/${MKBS_CONFIG[target]}"
    MKBS_BUILD_DIR="${MOONOS_ROOT}/build/${MKBS_CONFIG[target]}"
    MKBS_OUTPUT_DIR="${MOONOS_ROOT}/output/${MKBS_CONFIG[target]}"
    MKBS_REPO_DIR="${MKBS_CONFIG[repo-dir]:-${MOONOS_ROOT}/packages}"

    # Export for child processes
    export MKBS_ARCH MKBS_SYSROOT MKBS_TOOLCHAIN MKBS_BUILD_DIR MKBS_OUTPUT_DIR

    log_debug "Target: ${MKBS_CONFIG[target]}"
    log_debug "Arch: $MKBS_ARCH"
    log_debug "Sysroot: $MKBS_SYSROOT"
}

# Save configuration
mkbs_save_config() {
    log_debug "Saving configuration to $MKBS_CONFIG_FILE"

    cat > "$MKBS_CONFIG_FILE" << EOF
# MoonOS Build Configuration
# Generated by MKBS v${MKBS_VERSION}

target="${MKBS_CONFIG[target]}"
profile="${MKBS_CONFIG[profile]}"
kernel="${MKBS_CONFIG[kernel]}"
libc="${MKBS_CONFIG[libc]}"
init="${MKBS_CONFIG[init]}"
shell="${MKBS_CONFIG[shell]}"
compiler="${MKBS_CONFIG[compiler]}"
optimize="${MKBS_CONFIG[optimize]}"
jobs="${MKBS_CONFIG[jobs]}"
EOF
}

# Configure command
mkbs_configure() {
    log_step "Configure" "Setting up build environment"

    # Parse arguments
    while [[ $# -gt 0 ]]; do
        case "$1" in
            --target=*)
                MKBS_CONFIG[target]="${1#*=}"
                ;;
            --profile=*)
                MKBS_CONFIG[profile]="${1#*=}"
                ;;
            --kernel=*)
                MKBS_CONFIG[kernel]="${1#*=}"
                ;;
            --libc=*)
                MKBS_CONFIG[libc]="${1#*=}"
                ;;
            --init=*)
                MKBS_CONFIG[init]="${1#*=}"
                ;;
            --shell=*)
                MKBS_CONFIG[shell]="${1#*=}"
                ;;
            --compiler=*)
                MKBS_CONFIG[compiler]="${1#*=}"
                ;;
            *)
                log_error "Unknown configure option: $1"
                exit 1
                ;;
        esac
        shift
    done

    # Validate target
    if [[ -z "${MKBS_TARGETS[${MKBS_CONFIG[target]}]+x}" ]]; then
        log_error "Unsupported target: ${MKBS_CONFIG[target]}"
        log_error "Supported targets: ${!MKBS_TARGETS[*]}"
        exit 1
    fi

    # Validate profile
    if [[ -z "${MKBS_PROFILES[${MKBS_CONFIG[profile]}]+x}" ]]; then
        log_error "Unsupported profile: ${MKBS_CONFIG[profile]}"
        log_error "Supported profiles: ${!MKBS_PROFILES[*]}"
        exit 1
    fi

    # Initialize configuration
    mkbs_init_config

    # Create directory structure
    log_info "Creating directory structure"
    mkdir -p "$MKBS_SYSROOT"/{bin,sbin,lib,lib64,usr/{bin,sbin,lib,lib64,include},etc,var,proc,sys,dev,tmp}
    mkdir -p "$MKBS_TOOLCHAIN"
    mkdir -p "$MKBS_BUILD_DIR"
    mkdir -p "$MKBS_OUTPUT_DIR"
    mkdir -p "${MOONOS_ROOT}/cache"

    # Save configuration
    mkbs_save_config

    # Print configuration summary
    echo ""
    echo "=========================================="
    echo "  MoonOS Build Configuration"
    echo "=========================================="
    echo "  Target:    ${MKBS_CONFIG[target]}"
    echo "  Arch:      $MKBS_ARCH"
    echo "  Profile:   ${MKBS_CONFIG[profile]}"
    echo "  Kernel:    ${MKBS_CONFIG[kernel]}"
    echo "  Libc:      ${MKBS_CONFIG[libc]}"
    echo "  Init:      ${MKBS_CONFIG[init]}"
    echo "  Shell:     ${MKBS_CONFIG[shell]}"
    echo "  Compiler:  ${MKBS_CONFIG[compiler]}"
    echo "  Sysroot:   $MKBS_SYSROOT"
    echo "  Toolchain: $MKBS_TOOLCHAIN"
    echo "  Jobs:      $MKBS_JOBS"
    echo "=========================================="
    echo ""
    log_success "Configuration complete"
}

# Get configuration value
config_get() {
    local key="$1"
    echo "${MKBS_CONFIG[$key]:-}"
}

# Set configuration value
config_set() {
    local key="$1"
    local value="$2"
    MKBS_CONFIG[$key]="$value"
}
